apiVersion: v1
kind: Secret
metadata:
  name: portfolio-secret
  namespace: portfolio
  labels:
    app: portfolio
type: Opaque
stringData:
  DATABASE_URL: ""
  AUTH_SECRET: ""
  AUTH_URL: ""
  CLOUDINARY_CLOUD_NAME: ""
  CLOUDINARY_API_KEY: ""
  CLOUDINARY_API_SECRET: ""
  NEXT_PUBLIC_GA_ID: ""
